Fixes issue covering up test failures in bin/unit

diff --git a/bin/unit b/bin/unit
--- a/bin/unit
+++ b/bin/unit
@@ -16,8 +16,16 @@ source $DIR/env/$ENVIRONMENT
 function run() {
   set +e
   ginkgo -randomizeAllSpecs=true -randomizeSuites=true -succinct=true $@
-  EXIT_CODE=$?
+  if [[ $? != 0 ]]; then
+    fail $?
+  fi
   set -e
+}
+
+function fail() {
+  echo
+  echo -e "${RED}UNIT SUITE FAIL${NONE}"
+  exit $1
 }
 
 if [[ -z "$1" ]]; then
@@ -27,13 +35,5 @@ else
     run $@
 fi
 
-if [[ $EXIT_CODE = 0 ]]; then
-    STATE="${GREEN}UNIT SUITE PASS${NONE}"
-else
-    STATE="${RED}UNIT SUITE FAIL${NONE}"
-fi
-
-echo
-echo -e $STATE
-
+echo -e "${GREEN}UNIT SUITE PASS${NONE}"
 exit $EXIT_CODE
